### PR TITLE
Added a class logic adding different colors according to organism.species

### PR DESCRIPTION
**Pull request by sabinacuccibar**
Not urgent, but please review my work on index page
Screenshot 2021-01-30 at 13 00 00

### CODE REVIEW

**Comment by KseniiaNovinskaia** [comment]
Hey Sabina, looks great. now we can distinguish between different organism types. Will @jasonheeps' search bar will be visible there as well?

**Comment by Kimon-Haars** [comment]
looks good to me.

**Review by Kimon-Haars — APPROVED** [review]
testing out the "approve" functionality of this "review changes" button 😁

**Review by jasonheeps — APPROVED** [review]
The design looks good!

Another thing: It seems you haven't done a git pull origin master before working on this branch since the searchbar isn't there yet (unless you moved it into the navbar). I think it's okay for now since it's only one line of html and I can merge it in my next branch. 

Just a reminder to *always* run 'git pull origin master' before creating a new branch.

**Pull request merged**
